comur_image:
    config:
        cropped_image_dir: 'cropped'
        thumbs_dir: 'thumbnails'
        media_lib_thumb_size: 150
        public_dir: '%kernel.project_dir%/public/uploads'
        translation_domain: 'ComurImageBundle'
        gallery_thumb_size: 150
        gallery_dir: 'gallery'       