twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        deletemsg: return confirm('Eliminar item? Esta acción no se puede deshacer.');

