index_admin:
    path: /admin
    controller: App\Controller\DefaultController::index

index_remates:
    path: /catalogo
    controller: App\Controller\CatalogoController::index

profile:
    path: /catalogo
    controller: App\Controller\CatalogoController::index

generictable:
    path: /generictable
    controller: App\Controller\GenericController::getData
    options:
        expose: true

filterlotes:
    path: /filterlotes
    controller: App\Controller\GenericController::filterLotes
    options:
        expose: true
